### PR TITLE
Gnome 45 port

### LINKED ISSUE #130: GNOME 45 support
There are breaking changes which will require a separate release for 45 and <=44:

See https://gjs.guide/extensions/upgrading/gnome-shell-45.html

### PR DESCRIPTION
**Pull request by yilozt**
Now let's try to move this extension to Gnome 45. This PR do nothing, just update the `import` declarations for Gnome 45.

Fixes #130

You can help test this PR via open **Github Actions**: https://github.com/yilozt/rounded-window-corners/actions?query=branch%3Agnome-45-port, then download the extensions that pack from GitHub Actions:

[recording_.webm](https://github.com/yilozt/rounded-window-corners/assets/32430186/1ccbbf2f-fa15-4727-9196-faec4ee8cd65)

Then install extensions via:

```bash
cd ~/Downloads
gnome-extensions install ./rounded-window-corners@yilozt.shell-extension.zip  --force
```

Now you can help to test this extensions in Gnome 45~

Some problems to solve:

- [x] When you switch workspace via swipe gesture on touch-pad, you will find that shadow of window has gone when the animation running. Because the [`WorkspaceGroup`](https://github.com/GNOME/gnome-shell/blob/88fe5afe47440cef541aab5cf23c9996220e45ed/js/ui/workspaceAnimation.js#L20) class has been private in Gnome 45. We can't access it directly anymore. We need find a way to implement this features.
  Or you can install [Desktop Cube](https://extensions.gnome.org/extension/4648/desktop-cube/) and switch workspace by drag the desktop, you will find that the shadow we add for window has gone.
- [x] In ESM, we can't patch a export function directly. so we can't change the behaviour of [`addBackgroundMenu()`](https://github.com/GNOME/gnome-shell/blob/88fe5afe47440cef541aab5cf23c9996220e45ed/js/ui/backgroundMenu.js#L31) , this extensions can't add on popup menu to open preferences page when gnome-shell startup.
- [x] Use  `console.log()` to logging.
  https://gjs.guide/extensions/upgrading/gnome-shell-45.html#logging
- <del>[ ] Use  `libadwaita` for  preferences window ui?</del> *will finish this feature when i have free time.* 
- [x] Can't load translations.
- [x] Can't open shadow edit window

### CODE REVIEW

**Comment by gregor160300** [comment]
I've just tested this on Fedora 39 Beta, and it seems to work as you described, window shadow stay when using the workspace indicator or overview to switch, can't test touchpad switching as this is on desktop. I think `libadwaita` would be nice to have, but not required.

**Comment by veraguido** [comment]
tried it for a few hours already, works like a charm. Thanks!

**Comment by RyzenDew** [comment]
Works so well i will report any issues

**Comment by 2k16daniel** [comment]
No issue so far Let's goooo!!!!

**Comment by claytonwramsey** [comment]
Just tested this on Fedora 39 with an NVIDIA GPU. No issues with the extension - the only wrinkle was that I had to restart my shell session before the extension was fully installed.

**Comment by kir68k** [comment]
> The only wrinkle was that I had to restart my shell session before the extension was fully installed.

This seems to just be how the `gnome-extensions` command works, not specific to this plugin.
Can confirm on amdgpu this works well now.

**Comment by k1gen** [comment]
thanks, this works without issues for me!

**Comment by BobbieERay** [comment]
Thanks so much. Works without issues for me also so far. Just remember to restart gnome-extensions after the install.

**Comment by PJansky** [comment]
I've been using it for the last couple of days, I've seen no regressions

**Comment by AlexNabokikh** [comment]
works fine on ubuntu 23.10

**Comment by khalangy** [comment]
Works well for me too on Arch gnome 45.
Thanks @yilozt :smile:

**Comment by Fxsch** [comment]
I tested it on Arch as well and it seems to work perfectly fine

**Comment by pixlxip** [comment]
Works great for me... ArcoLinux, Gnome 45

**Comment by hsantos92** [comment]
This works for me. Arch, Gnome 45 👍🏼

**Comment by sidevesh** [comment]
works for me too on Arch, @yilozt can you rebase and get https://github.com/yilozt/rounded-window-corners/tree/rounded-all-windows-in-overview branch in before pushing this to gnome extensions ? I have been manually installing the version on that branch for quite some time but I wasn't able to rebase it on this pr and would really like to get the windows rounded in overview feature in the main branch and release so I can stop installing / maintaining the version on the branch

**Comment by qwqn69** [comment]
Works really good for me! tysm!!!! Fedora 39 Beta

**Comment by acerspyro** [comment]
Works great, thank you!

**Comment by joax** [comment]
Ubuntu 23.10 tested, works like a charm here.

**Comment by mbeps** [comment]
Thanks, now almost all the extensions that I like are on Gnome 45. Maybe by the time Fedora 39 is out, all my extensions would have been ported.

**Comment by Chillsmeit** [comment]
OpenSUSE Tumbleweed using Gnome 45, been using it for a week now. Works like a charm, 0 issues so far.

**Comment by jonhteper** [comment]
Tested on Manjaro Gnome 45, and woks without issues. Thanks for all.

**Comment by rezzubs** [comment]
Used the gnome 45 version for a few weeks now, no issues.

**Comment by anhng195** [comment]
Please release it on the extension store

**Comment by DavidWoli** [comment]
@yilozt Could you please merge it and release it on the extension store? Please...

**Comment by yilozt** [comment]
I am very sorry that i am too lazy recently, I will review and release new version in this weekend.😭😭😭😭😭发件人: DavidWoli ***@***.***>发送时间: 2023年11月7日星期二 23:01收件人: yilozt/rounded-window-corners ***@***.***>抄送: Yi ***@***.***>; Mention ***@***.***>主题: Re: [yilozt/rounded-window-corners] Gnome 45 port (PR #137)
@yilozt Could you please merge it and release it on the extension store? Please...

**Comment by sidevesh** [comment]
@yilozt Can you take a look at https://github.com/yilozt/rounded-window-corners/pull/137#issuecomment-1781499063 please ?

**Comment by yilozt** [comment]
I will take a looks for the PR to rounded all window in overview.

**Comment by saschaeggi** [comment]
I can confirm that using https://github.com/yilozt/rounded-window-corners/actions/runs/6839498020 works on Fedora 39 with Gnome 45

**Comment by AlexNabokikh** [comment]
@yilozt Can you release a new version so we can install it via GNOME extensions instead of manually using GitHub artifacts? Thank you!

**Comment by Majklovitch** [comment]
Apparently the Artifact expired and it's no longer for download. Is there a way I can get it?

**Comment by Fxsch** [comment]
I uploaded it [here](https://files.catbox.moe/d5kjvc.zip)

**Comment by Majklovitch** [comment]
Thanks, it's working perfectly and made the desktop whole lot cleaner. Cheers

**Pull request merged**
