### PR TITLE
Reimplement "Add option to make all window in overview be rounded"

### LINKED ISSUE #93: Round maximized and tiled windows in overview
Can we round the corners of maximized and tiled windows in overview, even if they are set to not have rounded corners in options ?
image

These stick out in overview with sharp corners and this would make the rounded windows aesthetic fully consistent.
Can this be implemented by this extension ?

### PR DESCRIPTION
**Pull request by sidevesh**
Closes #93

### CODE REVIEW

**Comment by ifelsemaybe** [comment]
Works on my machine.

**Comment by sidevesh** [comment]
I have just migrated the original code written by @yilozt on a branch but never merged to Gnome 45,
not sure why @yilozt is non responsive on this since almost a year despite writing the original code and taking the effort to upgrade the extension to Gnome 45 a while back.
@yilozt It would be great if you can merge this in so I can stop having to maintain this branch.

**Comment by ifelsemaybe** [comment]
They might just be busy. Sometimes life gets in the way man.

**Comment by ifelsemaybe** [comment]
Actually, one bug I'm noticing with your branch is that when I go in the overview, all the windows are blurred for some reason. If I disable the "Add rounded corners for all windows in overview" setting, inside Extensions, that blur disappears. So something is up. While scrolling through the commit history, I saw that this bug has been addressed before, https://github.com/yilozt/rounded-window-corners/commit/02f0ae80381c5db48fa3818bd4abf1c44bf9986d. Maybe this can offer some insight...

**Comment by ifelsemaybe** [comment]
While testing this issue a little further, I believe the blur shows itself in the overview to all windows that have rounded corners. So on the main branch, a window that has not been maximized, and shows up by default, rounded, in the overview, will also have this same problem. I might raise an issue for this, if it hasn't already been raised.

**Pull request closed without merging**
